### ISSUE TITLE
Source Sans Pro is not loading https version

### ISSUE THREAD

**Issue by markahrens** [ITS-UofIowa/stellar#6]
This is happening on both custom and standard service sites. Most browsers are still loading the font, however some versions of Safari are not.

Two sites where this is happening are:

https://desmoines.uiowa.edu
https://uiowa.edu/mural-film/

The error from mural-film is:

Mixed Content: The page at 'https://uiowa.edu/mural-film/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,400italic,700italic'. This request has been blocked; the content must be served over HTTPS.

**Comment by genjohnson** [comment]
This was a known issue during the migration to Acquia, and the fix (at least for Standard sites) was/is to edit the font source in the Appearance settings. The default font source was updated in the .info file on the 7.x-2.x branch to use https (see [line 88 of stellar.info](https://github.com/ITS-UofIowa/stellar/blob/7.x-2.x/stellar.info#L88), which is the branch used for Standard sites.

There are so few Standard sites using the Stellar theme that we opted not to spend development time writing an update hook for this in the midst of migrations.

If we get a report of sites using Stellar, one of the students could update these.

**Comment by genjohnson** [comment]
I've updated the font source for https://desmoines.uiowa.edu and https://uiowa.edu/mural-film/ to use https.

**Comment by markahrens** [comment]
Thanks @genjohnson. Will we also need to update the 1.x branch in the .info file too?

**Comment by genjohnson** [comment]
It looks like the Custom sites use the 1.x branch [(see line 148 of sitenow_custom_make)](https://github.com/ITS-UofIowa/sitenow_custom_profile/blob/7.x-2.x/custom.make.yml#L148), so yes, we will need to update the 1.x branch of Stellar.

I'll open a pull request for that now.

**Comment by adamdelaney** [comment]
It looks like the PR to fix this issue was merged so I'm closing this issue for now.
